name: igdb_wrapper
description: Dart API Wrapper
version: 1.1.0
homepage: https://github.com/NeoDigi/igdb_wrapper
author: Julien Tielemans <julien.tiel@gmail.com>

environment:
  sdk: '>=1.20.1 <3.0.0'

dependencies:
  http: "^0.11.3+16"

dev_dependencies:
  test: ^1.3.0
