name: igdb_wrapper
description: Dart API Wrapper
version: 1.0.0
homepage: https://github.com/neodigi/api-dart
author: Julien Tielemans <julien.tiel@gmail.com>

environment:
  sdk: '>=2.0.0-dev.55.0 <2.0.0'

dependencies:
  http: "^0.11.3+16"

dev_dependencies:
  test: ^0.12.30
